import React, { useState } from 'react';
import { 
  Calendar, 
  MapPin, 
  Clock, 
  Tag, 
  ExternalLink, 
  Printer, 
  Bookmark, 
  BookmarkCheck, 
  Share2, 
  Sparkles, 
  Wand2, 
  CheckCircle, 
  Circle, 
  Navigation, 
  Coffee, 
  Sun, 
  Sunset, 
  Moon, 
  CloudSun, 
  CalendarDays, 
  ArrowLeft, 
  Copy, 
  Check, 
  Download,
  UtensilsCrossed,
  Backpack,
  Wallet,
  ShieldCheck,
  Plane,
  ArrowRight,
  Lightbulb,
  Route,
  Bike
} from 'lucide-react';
import { TravelPlan, DayPlan, Activity, SupportedLanguage, CurrencyCode, PackingItem } from '../types';
import { BudgetSection } from './BudgetSection';
import { PackingSection } from './PackingSection';
import { FoodSection } from './FoodSection';
import { SafetySection } from './SafetySection';
import { RouteTransitSection } from './RouteTransitSection';
import { BikeTourSection } from './BikeTourSection';
import { AIAdviceSection } from './AIAdviceSection';
import { DayTweakModal } from './DayTweakModal';
import { WeatherWidget } from './WeatherWidget';
import confetti from 'canvas-confetti';

interface ItineraryViewProps {
  plan: TravelPlan;
  onSaveTrip: (plan: TravelPlan) => void;
  isSaved: boolean;
  onBackToPlanner: () => void;
  onOpenConcierge: () => void;
  onApplyDayTweak: (dayNumber: number, instruction: string) => Promise<void>;
  onUpdatePlan: (updatedPlan: TravelPlan) => void;
  language: SupportedLanguage;
  currency: CurrencyCode;
}

type TabType = 'timeline' | 'weather' | 'transit' | 'bike' | 'budget' | 'advice' | 'food' | 'packing' | 'safety';

export const ItineraryView: React.FC<ItineraryViewProps> = ({
  plan,
  onSaveTrip,
  isSaved,
  onBackToPlanner,
  onOpenConcierge,
  onApplyDayTweak,
  onUpdatePlan,
  language,
  currency,
}) => {
  const isHinglish = language === 'hi_hinglish';
  const [activeTab, setActiveTab] = useState<TabType>('timeline');
  const [selectedDayNumber, setSelectedDayNumber] = useState<number | 'all'>('all');
  const [tweakModalDay, setTweakModalDay] = useState<DayPlan | null>(null);
  const [copied, setCopied] = useState(false);

  const originName = plan.routeTransit?.origin || plan.startingCity || 'Delhi';

  const toggleActivityComplete = (dayNumber: number, activityId: string) => {
    const updatedDays = plan.days.map((day) => {
      if (day.dayNumber !== dayNumber) return day;
      return {
        ...day,
        activities: day.activities.map((act) => {
          if (act.id !== activityId) return act;
          return { ...act, isCompleted: !act.isCompleted };
        }),
      };
    });
    onUpdatePlan({ ...plan, days: updatedDays });
  };

  const handleTogglePacking = (id: string) => {
    const updated = plan.packingList.map((item) => 
      item.id === id ? { ...item, isChecked: !item.isChecked } : item
    );
    onUpdatePlan({ ...plan, packingList: updated });
  };

  const handleAddPackingItem = (name: string, category: PackingItem['category']) => {
    const newItem: PackingItem = {
      id: `custom-pack-${Date.now()}`,
      name,
      category,
      isChecked: false,
    };
    onUpdatePlan({ ...plan, packingList: [newItem, ...plan.packingList] });
  };

  const handleDeletePackingItem = (id: string) => {
    const updated = plan.packingList.filter((item) => item.id !== id);
    onUpdatePlan({ ...plan, packingList: updated });
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopySummary = () => {
    const originText = originName ? `${originName} ➔ ` : '';
    const summaryText = `✈️ ${originText}${plan.destination} (${plan.daysCount} Days Travel Plan)\n${plan.tagline}\n\nBudget: ${plan.budget.currency} ${plan.budget.totalEstimate.toLocaleString()} (${plan.budgetTier})\nBest Transit Mode: ${plan.routeTransit?.bestTravelMode || 'Flight / Train'}\nBest Time: ${plan.bestTimeToVisit}\n\nDay-by-Day Highlights:\n${plan.days.map(d => `Day ${d.dayNumber}: ${d.title}\n- ${d.activities.map(a => `${a.timeSlot}: ${a.title} (${a.locationName})`).join('\n- ')}`).join('\n\n')}\n\nAI Advice: ${plan.aiSmartAdvice?.overallVerdict || ''}\n\nGenerated by AI Travel Planner (Gemini 3.7)`;
    navigator.clipboard.writeText(summaryText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleSaveClick = () => {
    onSaveTrip(plan);
    if (!isSaved) {
      confetti({
        particleCount: 60,
        spread: 50,
        origin: { y: 0.6 },
      });
    }
  };

  const getTimeSlotIcon = (slot: string) => {
    switch (slot.toLowerCase()) {
      case 'morning':
        return <Sun className="w-4 h-4 text-amber-500" />;
      case 'afternoon':
        return <CloudSun className="w-4 h-4 text-orange-500" />;
      case 'evening':
        return <Sunset className="w-4 h-4 text-rose-500" />;
      case 'night':
        return <Moon className="w-4 h-4 text-indigo-500" />;
      default:
        return <Clock className="w-4 h-4 text-slate-500" />;
    }
  };

  const displayedDays = selectedDayNumber === 'all' 
    ? plan.days 
    : plan.days.filter((d) => d.dayNumber === selectedDayNumber);

  return (
    <div className="w-full max-w-5xl mx-auto space-y-6 pb-16">
      {/* Top Back & Action Header */}
      <div className="no-print flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <button
          onClick={onBackToPlanner}
          className="inline-flex items-center space-x-2 text-xs font-bold text-slate-600 hover:text-emerald-700 transition-colors self-start"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>{isHinglish ? 'Naya Plan / Route Badlein' : 'Create Another Itinerary'}</span>
        </button>

        <div className="flex flex-wrap items-center gap-2">
          {/* Ask AI Concierge */}
          <button
            onClick={onOpenConcierge}
            className="px-3.5 py-2 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-300 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-2xs"
          >
            <Sparkles className="w-3.5 h-3.5 text-emerald-600 animate-pulse" />
            <span>{isHinglish ? 'Ask AI Guide' : 'Ask AI Concierge'}</span>
          </button>

          {/* Copy plan */}
          <button
            onClick={handleCopySummary}
            className="px-3.5 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-2xs"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? (isHinglish ? 'Copied!' : 'Copied!') : (isHinglish ? 'Copy' : 'Share / Copy')}</span>
          </button>

          {/* Print / PDF */}
          <button
            onClick={handlePrint}
            className="px-3.5 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-2xs"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>{isHinglish ? 'Print / PDF' : 'Print / PDF'}</span>
          </button>

          {/* Save Button */}
          <button
            onClick={handleSaveClick}
            className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-all shadow-xs ${
              isSaved
                ? 'bg-emerald-600 text-white shadow-emerald-600/20'
                : 'bg-slate-900 hover:bg-slate-800 text-white'
            }`}
          >
            {isSaved ? <BookmarkCheck className="w-3.5 h-3.5" /> : <Bookmark className="w-3.5 h-3.5" />}
            <span>{isSaved ? (isHinglish ? 'Saved ✓' : 'Saved in App') : (isHinglish ? 'Save Trip' : 'Save Trip')}</span>
          </button>
        </div>
      </div>

      {/* Hero Destination Banner */}
      <div className="bg-gradient-to-br from-slate-900 via-slate-800 to-emerald-950 text-white rounded-3xl p-6 sm:p-8 shadow-xl shadow-slate-900/10 relative overflow-hidden border border-slate-700/50">
        <div className="absolute top-0 right-0 -mt-8 -mr-8 w-64 h-64 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="relative z-10 space-y-4">
          
          {/* Origin -> Destination Route Pill */}
          <div className="flex flex-wrap items-center gap-2">
            <div className="px-3 py-1 bg-emerald-500/25 text-emerald-300 border border-emerald-400/40 rounded-full text-xs font-extrabold flex items-center space-x-1.5">
              <span>{originName}</span>
              <ArrowRight className="w-3.5 h-3.5 text-emerald-400" />
              <span>{plan.destination}</span>
            </div>

            <span className="px-3 py-1 bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 rounded-full text-xs font-bold uppercase tracking-wider">
              {plan.daysCount} {plan.daysCount === 1 ? 'Day' : 'Days'}
            </span>
            <span className="px-3 py-1 bg-white/10 text-slate-200 border border-white/10 rounded-full text-xs font-semibold capitalize">
              {plan.budgetTier} Budget
            </span>
            <span className="px-3 py-1 bg-white/10 text-slate-200 border border-white/10 rounded-full text-xs font-semibold capitalize">
              {plan.travelerType}
            </span>
          </div>

          <div>
            <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight text-white flex items-center space-x-3">
              <span>{plan.destination}</span>
            </h1>
            <p className="text-emerald-300 font-semibold text-sm sm:text-base mt-1">
              "{plan.tagline}"
            </p>
          </div>

          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed max-w-3xl">
            {plan.summary}
          </p>

          {/* Quick Snapshot Badges */}
          <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 pt-3 border-t border-slate-700/80 text-xs">
            <div className="flex items-center space-x-2.5 bg-white/5 p-3 rounded-xl border border-white/5">
              <Route className="w-4 h-4 text-sky-400 shrink-0" />
              <div>
                <div className="text-[10px] text-slate-400 uppercase font-semibold">Best Transit Mode</div>
                <div className="font-bold text-slate-200 truncate">{plan.routeTransit?.bestTravelMode || 'Flights / Trains'}</div>
              </div>
            </div>

            <div className="flex items-center space-x-2.5 bg-white/5 p-3 rounded-xl border border-white/5">
              <CalendarDays className="w-4 h-4 text-emerald-400 shrink-0" />
              <div>
                <div className="text-[10px] text-slate-400 uppercase font-semibold">Best Time to Visit</div>
                <div className="font-bold text-slate-200 truncate">{plan.bestTimeToVisit}</div>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setActiveTab('weather')}
              className="flex items-center space-x-2.5 bg-white/5 hover:bg-white/10 p-3 rounded-xl border border-white/5 hover:border-amber-400/40 text-left transition-all group cursor-pointer"
              title="Click to view 5-Day Weather Forecast"
            >
              <CloudSun className="w-4 h-4 text-amber-400 shrink-0 group-hover:scale-110 transition-transform" />
              <div className="overflow-hidden">
                <div className="text-[10px] text-slate-400 uppercase font-semibold flex items-center justify-between">
                  <span>Weather Outlook</span>
                  <span className="text-[9px] text-amber-300 font-bold ml-1">5-Day ➔</span>
                </div>
                <div className="font-bold text-slate-200 truncate">{plan.weatherSummary}</div>
              </div>
            </button>

            <div className="flex items-center space-x-2.5 bg-white/5 p-3 rounded-xl border border-white/5">
              <Wallet className="w-4 h-4 text-cyan-400 shrink-0" />
              <div>
                <div className="text-[10px] text-slate-400 uppercase font-semibold">Total Trip Budget</div>
                <div className="font-bold text-slate-200">
                  {plan.budget.currency} {plan.budget.totalEstimate.toLocaleString()}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="no-print bg-white p-1.5 rounded-2xl border border-slate-200 shadow-2xs flex overflow-x-auto scrollbar-none gap-1">
        {[
          { id: 'timeline' as TabType, labelEn: 'Day-by-Day Plan', labelHi: 'Day-by-Day Schedule', icon: <Calendar className="w-4 h-4" /> },
          { id: 'weather' as TabType, labelEn: '5-Day Weather', labelHi: '🌤️ 5-Day Mausam', icon: <CloudSun className="w-4 h-4 text-sky-500" /> },
          { id: 'transit' as TabType, labelEn: 'Route & Transit Options', labelHi: 'Route & Transit Modes', icon: <Route className="w-4 h-4" /> },
          { id: 'bike' as TabType, labelEn: 'Bike & Petrol Guide', labelHi: '🏍️ Bike Route & Petrol', icon: <Bike className="w-4 h-4 text-amber-500" /> },
          { id: 'budget' as TabType, labelEn: 'Budget & Cost Breakdown', labelHi: 'Total Budget & Kharch', icon: <Wallet className="w-4 h-4" /> },
          { id: 'advice' as TabType, labelEn: 'AI Smart Advice & Hacks', labelHi: 'AI Advice & Tips', icon: <Lightbulb className="w-4 h-4" /> },
          { id: 'food' as TabType, labelEn: 'Food & Dining', labelHi: 'Food & Zayka', icon: <UtensilsCrossed className="w-4 h-4" /> },
          { id: 'packing' as TabType, labelEn: 'Packing Checklist', labelHi: 'Packing List', icon: <Backpack className="w-4 h-4" /> },
          { id: 'safety' as TabType, labelEn: 'Safety & Etiquette', labelHi: 'Safety & Rules', icon: <ShieldCheck className="w-4 h-4" /> },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={`flex-1 min-w-[130px] py-2.5 px-3 rounded-xl text-xs font-bold flex items-center justify-center space-x-1.5 transition-all shrink-0 ${
              activeTab === tab.id
                ? 'bg-emerald-600 text-white shadow-xs'
                : 'text-slate-600 hover:text-slate-900 hover:bg-slate-50'
            }`}
          >
            {tab.icon}
            <span>{isHinglish ? tab.labelHi : tab.labelEn}</span>
          </button>
        ))}
      </div>

      {/* Tab 1: Day-by-Day Timeline */}
      {activeTab === 'timeline' && (
        <div className="space-y-6">
          {/* Integrated 5-Day Weather Forecast Widget on Timeline Overview */}
          <WeatherWidget
            destination={plan.destination}
            initialStartDate={plan.startDate}
            weatherSummary={plan.weatherSummary}
            initialWeather={plan.weatherForecast}
            language={language}
            onDateChange={(newDate) => {
              onUpdatePlan({ ...plan, startDate: newDate });
            }}
          />

          {/* Day Filter Pills */}
          <div className="no-print flex items-center gap-1.5 overflow-x-auto pb-1 scrollbar-none">
            <button
              onClick={() => setSelectedDayNumber('all')}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all shrink-0 ${
                selectedDayNumber === 'all'
                  ? 'bg-slate-900 text-white shadow-xs'
                  : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
              }`}
            >
              {isHinglish ? 'All Days' : 'All Days'} ({plan.days.length})
            </button>
            {plan.days.map((d) => (
              <button
                key={d.dayNumber}
                onClick={() => setSelectedDayNumber(d.dayNumber)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all shrink-0 ${
                  selectedDayNumber === d.dayNumber
                    ? 'bg-emerald-600 text-white shadow-xs'
                    : 'bg-white border border-slate-200 text-slate-600 hover:bg-slate-50'
                }`}
              >
                Day {d.dayNumber}
              </button>
            ))}
          </div>

          {/* Days List */}
          <div className="space-y-6">
            {displayedDays.map((day) => (
              <div 
                key={day.dayNumber} 
                className="bg-white border border-slate-200 rounded-3xl p-5 sm:p-7 shadow-xs space-y-5 print-break-inside-avoid"
              >
                {/* Day Header */}
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-100">
                  <div className="flex items-start space-x-3.5">
                    <div className="w-11 h-11 rounded-2xl bg-emerald-600 text-white font-extrabold text-sm flex items-center justify-center shrink-0 shadow-sm shadow-emerald-600/30">
                      D{day.dayNumber}
                    </div>
                    <div>
                      <div className="flex items-center space-x-2">
                        <span className="text-xs font-bold text-emerald-700 uppercase tracking-wider">
                          Day {day.dayNumber} • {day.theme}
                        </span>
                      </div>
                      <h3 className="text-lg font-bold text-slate-900 tracking-tight">
                        {day.title}
                      </h3>
                      <p className="text-xs text-slate-500 mt-0.5">
                        {day.summary}
                      </p>
                    </div>
                  </div>

                  {/* Tweak Day Button */}
                  <button
                    onClick={() => setTweakModalDay(day)}
                    className="no-print self-start sm:self-auto px-3 py-1.5 bg-slate-100 hover:bg-emerald-50 text-slate-700 hover:text-emerald-800 border border-slate-200 hover:border-emerald-300 rounded-xl text-xs font-bold flex items-center space-x-1.5 transition-colors shadow-2xs"
                  >
                    <Wand2 className="w-3.5 h-3.5 text-emerald-600" />
                    <span>{isHinglish ? 'AI se Tweak karein' : 'Tweak with AI'}</span>
                  </button>
                </div>

                {/* Activities Timeline */}
                <div className="space-y-3">
                  <div className="text-xs font-extrabold text-slate-400 uppercase tracking-wider">
                    {isHinglish ? 'Activities & Itinerary Timeline' : 'Planned Activities & Sightseeing'}
                  </div>

                  <div className="grid grid-cols-1 gap-3">
                    {day.activities.map((act) => (
                      <div
                        key={act.id}
                        className={`p-4 rounded-2xl border transition-all ${
                          act.isCompleted
                            ? 'bg-emerald-50/40 border-emerald-200 opacity-80'
                            : 'bg-slate-50/70 hover:bg-white border-slate-200 hover:border-emerald-300 shadow-2xs hover:shadow-sm'
                        }`}
                      >
                        <div className="flex items-start justify-between gap-3">
                          <div className="flex items-start space-x-3 flex-1">
                            {/* Completion checkbox */}
                            <button
                              type="button"
                              onClick={() => toggleActivityComplete(day.dayNumber, act.id)}
                              className="mt-0.5 text-emerald-600 hover:text-emerald-700 shrink-0"
                              title={act.isCompleted ? 'Mark as incomplete' : 'Mark as done'}
                            >
                              {act.isCompleted ? (
                                <CheckCircle className="w-5 h-5 fill-emerald-600 text-white" />
                              ) : (
                                <Circle className="w-5 h-5 text-slate-300 hover:text-emerald-500" />
                              )}
                            </button>

                            <div className="space-y-1.5 flex-1">
                              <div className="flex flex-wrap items-center gap-2">
                                <span className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded-md text-[11px] font-bold bg-white text-slate-700 border border-slate-200 shadow-2xs">
                                  {getTimeSlotIcon(act.timeSlot)}
                                  <span>{act.timeSlot}</span>
                                </span>
                                {act.timeRange && (
                                  <span className="text-[11px] font-semibold text-slate-500">
                                    {act.timeRange}
                                  </span>
                                )}
                                {act.approxCost !== undefined && (
                                  <span className="text-[11px] font-bold text-emerald-800 bg-emerald-100/80 px-2 py-0.5 rounded-md">
                                    {act.costCurrency || plan.budget.currency} {act.approxCost === 0 ? 'Free' : act.approxCost}
                                  </span>
                                )}
                              </div>

                              <h4 className={`text-sm font-bold ${act.isCompleted ? 'line-through text-slate-400' : 'text-slate-900'}`}>
                                {act.title}
                              </h4>

                              <p className="text-xs text-slate-600 leading-relaxed">
                                {act.description}
                              </p>

                              {/* Tags & Transport Tip */}
                              <div className="flex flex-wrap items-center gap-2 pt-1">
                                {act.locationName && (
                                  <a
                                    href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(act.mapQuery || `${act.locationName} ${plan.destination}`)}`}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="inline-flex items-center space-x-1 text-[11px] font-semibold text-emerald-700 hover:text-emerald-900 hover:underline bg-emerald-50 px-2 py-0.5 rounded-md border border-emerald-200"
                                  >
                                    <MapPin className="w-3 h-3 text-emerald-600" />
                                    <span>{act.locationName}</span>
                                    <ExternalLink className="w-2.5 h-2.5 opacity-70" />
                                  </a>
                                )}

                                {act.transportTip && (
                                  <span className="inline-flex items-center space-x-1 text-[11px] font-medium text-slate-600 bg-slate-100 px-2 py-0.5 rounded-md">
                                    <Navigation className="w-3 h-3 text-slate-400" />
                                    <span>{act.transportTip}</span>
                                  </span>
                                )}

                                {act.tags?.map((tag, tIdx) => (
                                  <span key={tIdx} className="text-[10px] font-medium text-slate-500 bg-white border border-slate-200 px-1.5 py-0.5 rounded">
                                    #{tag}
                                  </span>
                                ))}
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Day Meals Section */}
                {day.meals && (
                  <div className="bg-amber-50/50 border border-amber-200/70 rounded-2xl p-4">
                    <div className="text-[11px] font-bold text-amber-900 uppercase tracking-wider mb-2 flex items-center space-x-1.5">
                      <Coffee className="w-3.5 h-3.5 text-amber-700" />
                      <span>{isHinglish ? 'Khaane-Peene ke Suggestions' : 'Day Dining Recommendations'}</span>
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 text-xs">
                      {day.meals.breakfast && (
                        <div className="bg-white/80 p-2.5 rounded-xl border border-amber-200/50">
                          <span className="font-bold text-amber-950 block text-[11px]">🍳 Breakfast</span>
                          <span className="text-slate-600 text-[11px]">{day.meals.breakfast}</span>
                        </div>
                      )}
                      {day.meals.lunch && (
                        <div className="bg-white/80 p-2.5 rounded-xl border border-amber-200/50">
                          <span className="font-bold text-amber-950 block text-[11px]">🍱 Lunch</span>
                          <span className="text-slate-600 text-[11px]">{day.meals.lunch}</span>
                        </div>
                      )}
                      {day.meals.dinner && (
                        <div className="bg-white/80 p-2.5 rounded-xl border border-amber-200/50">
                          <span className="font-bold text-amber-950 block text-[11px]">🍲 Dinner</span>
                          <span className="text-slate-600 text-[11px]">{day.meals.dinner}</span>
                        </div>
                      )}
                    </div>
                  </div>
                )}

                {/* Day Pro Tip */}
                {day.localProTip && (
                  <div className="bg-emerald-50 border border-emerald-200 rounded-2xl p-3.5 flex items-start space-x-2.5 text-xs text-emerald-950">
                    <span className="text-emerald-700 font-bold shrink-0">💡 Pro-Tip:</span>
                    <span className="text-emerald-900 leading-relaxed font-medium">{day.localProTip}</span>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Tab 2: Dedicated 5-Day Weather Forecast */}
      {activeTab === 'weather' && (
        <div className="space-y-6">
          <WeatherWidget
            destination={plan.destination}
            initialStartDate={plan.startDate}
            weatherSummary={plan.weatherSummary}
            initialWeather={plan.weatherForecast}
            language={language}
            onDateChange={(newDate) => {
              onUpdatePlan({ ...plan, startDate: newDate });
            }}
          />
        </div>
      )}

      {/* Tab 3: Route Transit */}
      {activeTab === 'transit' && (
        <RouteTransitSection
          routeTransit={plan.routeTransit}
          origin={originName}
          destination={plan.destination}
          language={language}
          currency={currency}
        />
      )}

      {/* Tab 3: Bike Tour & Petrol Guide */}
      {activeTab === 'bike' && (
        <BikeTourSection
          bikeGuide={plan.bikeTripGuide}
          origin={originName}
          destination={plan.destination}
          language={language}
          currency={currency}
        />
      )}

      {/* Tab 4: Budget */}
      {activeTab === 'budget' && (
        <BudgetSection
          budget={plan.budget}
          routeTransit={plan.routeTransit}
          daysCount={plan.daysCount}
          language={language}
          currency={currency}
        />
      )}

      {/* Tab 4: AI Smart Advice */}
      {activeTab === 'advice' && (
        <AIAdviceSection
          advice={plan.aiSmartAdvice}
          destination={plan.destination}
          origin={originName}
          language={language}
        />
      )}

      {/* Tab 5: Food */}
      {activeTab === 'food' && (
        <FoodSection
          foods={plan.foodRecommendations}
          destination={plan.destination}
          language={language}
        />
      )}

      {/* Tab 6: Packing */}
      {activeTab === 'packing' && (
        <PackingSection
          items={plan.packingList}
          onToggleItem={handleTogglePacking}
          onAddItem={handleAddPackingItem}
          onDeleteItem={handleDeletePackingItem}
          language={language}
        />
      )}

      {/* Tab 7: Safety */}
      {activeTab === 'safety' && (
        <SafetySection
          data={plan.emergencyAndEtiquette}
          destination={plan.destination}
          language={language}
        />
      )}

      {/* Day Tweak AI Modal */}
      <DayTweakModal
        isOpen={!!tweakModalDay}
        onClose={() => setTweakModalDay(null)}
        dayPlan={tweakModalDay}
        destination={plan.destination}
        onApplyTweak={onApplyDayTweak}
        language={language}
      />
    </div>
  );
};
